-- CreateEnum
CREATE TYPE "AuditAction" AS ENUM ('LOGIN', 'LOGOUT', 'CREATE_USER', 'UPDATE_USER', 'DELETE_USER', 'CREATE_CUSTOMER', 'UPDATE_CUSTOMER', 'DELETE_CUSTOMER', 'CREATE_LOAN_PRODUCT', 'UPDATE_LOAN_PRODUCT', 'DELETE_LOAN_PRODUCT', 'CREATE_LOAN_APPLICATION', 'UPDATE_LOAN_APPLICATION', 'APPROVE_LOAN_APPLICATION', 'REJECT_LOAN_APPLICATION', 'CREATE_LOAN', 'APPROVE_LOAN', 'DISBURSE_LOAN', 'UPDATE_LOAN', 'CLOSE_LOAN', 'RECORD_REPAYMENT', 'REVERSE_REPAYMENT', 'MARK_OVERDUE', 'APPLY_PENALTY', 'WAIVE_PENALTY', 'CREATE_COLLECTION', 'UPDATE_COLLECTION', 'WRITE_OFF_LOAN', 'REVERSE_WRITE_OFF', 'SYSTEM');

-- CreateTable
CREATE TABLE "LoanPenalty" (
    "id" TEXT NOT NULL,
    "loanId" TEXT NOT NULL,
    "amount" DECIMAL(65,30) NOT NULL,
    "penaltyRate" DECIMAL(65,30) NOT NULL,
    "appliedDate" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "LoanPenalty_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "LoanPenalty_loanId_idx" ON "LoanPenalty"("loanId");

-- CreateIndex
CREATE UNIQUE INDEX "LoanPenalty_loanId_appliedDate_key" ON "LoanPenalty"("loanId", "appliedDate");

-- AddForeignKey
ALTER TABLE "LoanPenalty" ADD CONSTRAINT "LoanPenalty_loanId_fkey" FOREIGN KEY ("loanId") REFERENCES "Loan"("id") ON DELETE CASCADE ON UPDATE CASCADE;
